### ISSUE TITLE
Remove unused using statements

### ISSUE THREAD

**Issue by Ashera138** [Ashera138/ADHDmail#2]
<h2>Issue: There are many using statements throughout the files in this project that aren't being used. These should be removed.</h2>

This is a small and easy issue specifically for 🌱  new contributors 🌱 to try so they can get the hang of the contribution process rather than the contribution itself.

If you need a guide on how to contribute, check out [this README](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

If you have any questions or get stuck, feel free to comment below and I will answer all questions as best I can! 🌞

**Comment by Ashera138** [comment]
This issue is open again for any new contributors who want to give it a try!

**Comment by Colton-Bouchard** [comment]
I'll take this!

**Comment by Colton-Bouchard** [comment]
I have a PR open for this now. I can make another pr to handle some other minor resharper cleanup stuff if you want?

**Comment by Ashera138** [comment]
At a glance, [GlobalValues.cs](https://github.com/Ashera138/ADHDmail/blob/master/src/ADHDmail/GlobalValues.cs) (which is new) has some that can be removed. And in the test project, there's [ExtensionsTests](https://github.com/Ashera138/ADHDmail/blob/master/src/ADHDmailTests/ExtensionsTests.cs) and both of [these files](https://github.com/Ashera138/ADHDmail/tree/master/src/ADHDmailTests/Mocks).

Anyone is welcome to this.

**Comment by lvictorino** [comment]
I'll do it if that's ok.

**Comment by santhoshrajr** [comment]
@Ashera138 is the issue still Open?

**Comment by Ashera138** [comment]
@santhoshrajr Yep! Feel free to submit a PR for it.

**Comment by Ashera138** [comment]
I'll open this back up when I see more again. 👍
